USE [master]
GO

/****** Object:  Database [BDD_Cuarenta]    Script Date: 18/10/2020 11:45:54 ******/
CREATE DATABASE [BDD_Cuarenta]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BDD_Cuarenta', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BDD_Cuarenta.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BDD_Cuarenta_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BDD_Cuarenta_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BDD_Cuarenta].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BDD_Cuarenta] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BDD_Cuarenta] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BDD_Cuarenta] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BDD_Cuarenta] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BDD_Cuarenta] SET ARITHABORT OFF 
GO

ALTER DATABASE [BDD_Cuarenta] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BDD_Cuarenta] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BDD_Cuarenta] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BDD_Cuarenta] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BDD_Cuarenta] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BDD_Cuarenta] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BDD_Cuarenta] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BDD_Cuarenta] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BDD_Cuarenta] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BDD_Cuarenta] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BDD_Cuarenta] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BDD_Cuarenta] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BDD_Cuarenta] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BDD_Cuarenta] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BDD_Cuarenta] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BDD_Cuarenta] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BDD_Cuarenta] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BDD_Cuarenta] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BDD_Cuarenta] SET  MULTI_USER 
GO

ALTER DATABASE [BDD_Cuarenta] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BDD_Cuarenta] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BDD_Cuarenta] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BDD_Cuarenta] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BDD_Cuarenta] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BDD_Cuarenta] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BDD_Cuarenta] SET  READ_WRITE 
GO

